version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "build application"
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "build application"
          command: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "build application"
          command: npm audit

workflows:
  build-test-analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
